#!/bin/sh
echo Updating brew...
brew update

echo Upgrading installed forumlas...
brew upgrade

echo Installing custom list of formulas...
brew install colordiff
brew install colormake
brew install git
brew install pianobar
brew install python3
brew install unrar
brew install wget
brew install macvim
brew install aria2

# link apps
brew linkapps macvim

# Old brew cask section
# Now using Amphetamine from Mac App Store
brew install iterm2
brew install macs-fan-control
brew install scroll-reverser
brew install sublime-text
brew install sublime-merge
brew install beyond-compare
brew install forklift

brew cleanup -s

echo In the past, this is where I suggest you to check setup_vim.
echo Now, that vundle is pretty much dead, this section needs a rework.
