#!/bin/sh
echo Updating brew...
brew update

echo Upgrading installed forumlas...
brew upgrade

echo Installing custom list of formulas...
brew install cmake
brew install colordiff
brew install colormake
brew install ctags
brew install fortune
brew install ffmpeg --with-libvorbis --with-faac
brew install git --with-pcre --with-gettext
brew install pianobar
brew install sqlite --with-fts
brew install python
brew install unrar
brew install wget --enable-iri
brew install rbenv
brew install macvim --with-lua --with-override-system-vim
brew install aria2

# link apps
brew linkapps macvim

# homebrew-cask section!
brew tap caskroom/cask
brew cask update

# Now using Amphetamine from Mac App Store
# brew cask install keepingyouawake
# brew cask install nosleep
brew cask install iterm2
brew cask install macs-fan-control
brew cask install scroll-reverser

brew cleanup -s
brew cask cleanup

echo Be sure to take a look at setup_mvim to properly config macvim.
