#!/usr/local/bin/zsh

# Only execute this if we are in OSX
if [[ "$OSTYPE" == "darwin"* ]]; then
	echo Creating Directory ${HOME}/.zsh
	mkdir -p ${HOME}/.zsh

	echo Setting ZDOTDIR to ${HOME}/.zsh
	export ZDOTDIR=${HOME}/.zsh

	git clone --recursive https://github.com/thezoc/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

	setopt EXTENDED_GLOB
	for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
	  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
	done

	pushd

	cd "${ZDOTDIR:-$HOME}/.zprezto"

	git remote add upstream https://github.com/sorin-ionescu/prezto.git
	git fetch upstream
	git checkout master
	git submodule update --init --recursive
	echo Be sure to take a look at the utility update_prezto to fully update the install

	popd
else
	echo This script is only compatible with MacOS X at the time.
fi
