#!/bin/sh

# Only execute this if we are in OSX
if [[ "$OSTYPE" == "darwin"* ]]; then
	echo Updating homebrew...
	brew update
	
	echo Upgrading all installed packages...
	brew upgrade

	echo Installing zsh...
	brew install zsh

	echo Adding brew zsh to /etc/shells
	sudo sh -c "echo '/usr/local/bin/zsh' >> /etc/shells"

	echo Setting $HOME/.zsh as default zsh dot directory...
	sudo sh -c "echo 'export ZDOTDIR=\"\${HOME}/.zsh\"' >> /etc/zshenv"

	echo Changing default shell to zsh
	chsh -s /usr/local/bin/zsh

	./install_zsh_part2
else
	echo This script is only compatible with MacOS X at the time.
fi
