#!/bin/sh
pip install --upgrade pip
pip3 install --upgrade pip
pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs pip install -U
pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs pip install -U

