#!/bin/bash

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

vim -v +PluginInstall +qall

if [[ "$OSTYPE" == "darwin"* ]]; then
	brew update
	brew install cmake
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
	sudo apt-get install build-essential cmake python3 python3-dev
fi

# Compile YouCompleteMe
pushd .
cd ~/.vim/bundle/YouCompleteMe/
python3 install.py --clang-completer
popd

# Compile color_coded
pushd .
cd ~/.vim/bundle/color_coded
pwd
mkdir build
cd build
cmake ..
make && make install # Compiling with GCC is preferred, ironically
# Clang works on OS X, but has mixed success on Linux and the BSDs

# Cleanup afterward; frees several hundred megabytes
make clean && make clean_clang
popd
popd

